# Generated by Django 2.2.6 on 2021-04-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210427_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Все записи'},
        ),
    ]
