# Generated by Django 2.2.6 on 2021-04-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210427_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Все группы'},
        ),
    ]
